export { default as Home } from "./Home/Home";
export { default as  Header} from "./Header/Header";
export { default as  Footer} from "./Footer/Footer";
export { default as  AboutUs} from "./pages/AboutUs/AboutUs";
export { default as Collection} from "./pages/Collection/Collection";
export { default as ContactUs} from "./pages/ContactUs/ContactUs";
export { default as SignIN} from "./pages/Profile/Dashboard/Dashboard";
export { default as SignUP} from "./pages/SignUP/SignUP";
export { default as Subcription} from "./pages/Subcription/Subcription";
export { default as Dashboard} from "./pages/Profile/Dashboard/Dashboard";
// export { default as  } from "./";
